# Generated by Django 4.2.2 on 2023-09-20 06:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_planner', '0002_user_created_at_user_description_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
